### ISSUE TITLE
How to generate random instructions files?

### ISSUE THREAD

**Issue by yinhanquan** [openhwgroup/core-v-isg#9]
I have run `make comp SIMULATOR=<sim>` to compile the ISG and `make run SIMULATOR=<sim>` to compile and run it ,but there is no any files about instructions .

**Comment by MikeOpenHWGroup** [comment]
Hi @yinhanquan, please review the [corev-dv generated tests](https://github.com/openhwgroup/core-v-verif/tree/master/cv32/sim/uvmt_cv32#corev-dv-generated-tests) section of the README in the `cv32/sim/uvmtcv32` directory for instructions concerning the use of instruction generator.

**Comment by MikeOpenHWGroup** [comment]
Hi @yinhanquan, the user documentation for this project is not yet available.

**Comment by yinhanquan** [comment]
I have focused on research about riscv-dv,and now I am very interested in this project.

**Comment by MikeOpenHWGroup** [comment]
I would recommend you look at [riscv-dv](https://github.com/google/riscv-dv), the random instruction stream generator from Google.   We have used this in the [core-v-verif](https://github.com/openhwgroup/core-v-verif) project to verify the [cv32e40p](https://github.com/openhwgroup/cv32e40p).  Another good option is [force-riscv](https://github.com/openhwgroup/force-riscv).

I will close this issue now.  If you have any other questions, please reach out to me directly at mike@openhwgroup.org.
